name: npm package deploy
on:
  workflow_dispatch:

  push:
    tags:
      - "v*" # Runs only when a tag like v1.0.0 is pushed

  workflow_call:
    inputs:
      build-artifacts:
        type: boolean
        required: true
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Update version in package.json
        run: |
          cd projects/invensys-angular-shared
          npm version $VERSION --no-git-tag-version

      - name: Build Angular library
        run: npm run build invensys-angular-shared

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/invensys-angular-shared
          npm publish --access public
