name: ftp integra-flow deploy
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - ".scripts/**"
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md
    types:
      - closed
  workflow_call:
    inputs:
      build-artifacts:
        type: boolean
        required: true
        default: false
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from branch name
        run: echo "VERSION=${GITHUB_REF#refs/heads/release/v}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Update version in package.json
        run: npm version $VERSION --no-git-tag-version

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Publish package to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
